name: Deploy to Remote Server

on:
  push:
    branches:
      - main

env:
  SSH_HOST: myserver.com
  SSH_PORT: 22
  SSH_USER: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: shimataro/setup-ssh-action@v1
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: SSH to Remote Server
        run: |
          ssh -p ${{ env.PORT }} ${{ env.USER }}@${{ env.HOST }}
