name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  EC2_HOST: ${{ secrets.HOST }}
  EC2_USER: ${{ secrets.USER }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "$PRIVATE_KEY" | tr -d '\r' > id_rsa
          chmod 600 id_rsa
          eval "$(ssh-agent -s)"
          ssh-add id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            cd ./heala-auth-sevice
            git pull origin main
          EOF
